apiVersion: v1
kind: Secret
metadata:
  name: sqlpassword
type: Opaque
stringData:
  password: Microsoft123!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - image: 372476512951.dkr.ecr.eu-central-1.amazonaws.com/mysqlapi:1.0
        name: api
        ports:
        - containerPort: 8080
        env:
        - name: SQL_SERVER_FQDN
          value: "10.0.0.14"
        - name: SQL_SERVER_DB
          value: "test"
        - name: SQL_SERVER_USERNAME
          value: "mysqluser"
        - name: SQL_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpassword
              key: password
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: api
